### ISSUE TITLE
AppStore safe?

### ISSUE THREAD

**Issue by drd27** [HsiangHo/AppStoreUpdateKit#9]
Looks nice, but does this pass App Review? 
Last attempts to add update checks or an update mechanism, even if going through the App Store, have always resulted in rejections for me.

**Comment by HsiangHo** [comment]
@drd27 Sure, I've added this feature into one of my app on Mac App Store. Just see here https://github.com/HsiangHo/Kaka . How to pass the App Review, there is a trick. Please find the code snippet about the AppStoreUpdateKit function call in project 'Kaka' and you'll get the key.
